owner: Raksha-ch
repo: upptime

sites:
  - name: Raksha.ch
    url: https://raksha.ch
  - name: Raksha Mail - Mailu
    url: https://mail.raksha.ch
  - name: Raksha Mail - IMAP reception
    check: "tcp-ping"
    url: mail.raksha.ch
    port: 143
  - name: Raksha Mail - SMTP submission
    check: "tcp-ping"
    url: mail.raksha.ch
    port: 587
  - name: Raksha Mail - SMTP reception
    check: "tcp-ping"
    url: mail.raksha.ch
    port: 25

status-website:
  cname: status.raksha.ch
  logoUrl: https://raksha.ch/wp-content/uploads/2023/02/Raksha.png
  name: Raksha - État des services
  introTitle: "État des services Raksha.ch"
  introMessage: "Pour toutes question; admin+status@raksha.ch"
  navbar:
    - title: Homepage
      href: https://raksha.ch/
    - title: Raksha Mail
      href: https://mail.raksha.ch/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
