owner: Raksha-ch
repo: upptime

sites:
  - name: Homepage
    url: https://raksha.ch
  - name: Mailu
    url: https://mail.raksha.ch
  - name: IMAP
    check: "tcp-ping"
    url: mail.raksha.ch
    port: 143
  - name: Submission SMTP
    check: "tcp-ping"
    url: mail.raksha.ch
    port: 587
  - name: SMTP
    check: "tcp-ping"
    url: mail.raksha.ch
    port: 25

status-website:
  cname: status.raksha.ch
  logoUrl: https://raksha.ch/wp-content/uploads/2023/02/Raksha.png
  name: Raksha status
  introTitle: "Status of all the Raksha services"
  introMessage: ""
  navbar:
    - title: Homepage
      href: https://raksha.ch/
    - title: Raksha mail
      href: https://mail.raksha.ch/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
